services:
  - type: web
    name: newananas
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /app
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
    buildCommand: |
      pip install -e .
      python -c "import tensorflow as tf; tf.keras.backend.clear_session()"
    startCommand: gunicorn -c gunicorn_config.py web.app:app
    autoDeploy: true
    disk:
      name: newananas-data
      mountPath: /app/data
      sizeGB: 1
    healthCheck:
      httpPath: /api/health
      port: 10000
      initialDelaySeconds: 60  # Увеличено время ожидания
      periodSeconds: 60
      timeoutSeconds: 30
      successThreshold: 1
      failureThreshold: 3
    metrics:
      - port: 10000
        path: /metrics
    domains:
      - newananas.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /
