services:
  - type: web
    name: newananas
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    websocket: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /app
      - key: WORKERS
        value: "1"
      - key: TIMEOUT
        value: "300"
      - key: WORKER_CLASS
        value: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SOCKETIO_ASYNC_MODE
        value: gevent
      - key: SENTRY_DSN
        sync: false
      - key: NEW_RELIC_LICENSE_KEY
        sync: false
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements/prod.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:$PORT web.app:app
    autoDeploy: true
    disk:
      name: newananas-data
      mountPath: /app/data
      sizeGB: 1
    healthCheck:
      httpPath: /api/health
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 30
      successThreshold: 1
      failureThreshold: 3
