services:
  - type: web
    name: newananas
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8
      - key: PYTHONPATH
        value: /app
    buildCommand: pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 web.app:app
    autoDeploy: true
    disk:
      name: newananas-data
      mountPath: /app/data
      sizeGB: 1
    healthCheck:
      httpPath: /api/health
      port: 10000
      initialDelaySeconds: 30
      periodSeconds: 60
    metrics:
      - port: 10000
        path: /metrics
    domains:
      - newananas.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /
